language: php

php:
  - 5.5
  - 5.6

before_script:
  - mkdir -p ~/.composer
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer self-update
  - composer update --prefer-source --dev --no-interaction

script: 
  - vendor/bin/phpunit